#version 450
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba32f) uniform readonly image2D normals;
layout(binding = 1, rgba32f) uniform readonly image2D meshIds;
layout(set = 0, binding = 2) uniform sampler2D depths;
//layout(binding = 3, rgba32f) uniform readonly image2D rtOutput;
layout(binding = 3, rgba8)   uniform writeonly image2D outImage;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = 0.1 * imageLoad(normals, coord);
    imageStore(outImage, coord, color); // Just passthrough
}
